from __future__ import annotations

from .analytics import (
    get_aggregated_analytics,
    get_last_analytics_date,
    get_playlist_aggregated_analytics,
    get_playlist_top_videos_by_views,
    get_top_videos_by_views,
    get_video_analytics,
    upsert_video_analytics,
)
from .connection import get_connection, init_db
from .fx_rates import get_fx_rates, get_last_fx_rate, upsert_fx_rate
from .playlists import (
    delete_playlist_items,
    delete_playlists_not_in,
    get_all_playlists,
    get_playlist,
    get_playlist_videos,
    upsert_playlist,
    upsert_playlist_item,
)
from .sync_runs import (
    complete_sync_run,
    create_sync_run,
    fail_sync_run,
    get_last_successful_run_completed_at,
    get_sync_runs,
)
from .traffic_sources import (
    get_aggregated_traffic_sources,
    get_last_traffic_source_date,
    get_playlist_aggregated_traffic_sources,
    get_playlist_top_videos_by_traffic_source,
    get_top_videos_by_traffic_source,
    get_video_traffic_sources,
    upsert_video_traffic_source,
)
from .videos import (
    delete_videos_not_in,
    get_all_video_ids,
    get_all_videos,
    get_earliest_published_year,
    get_playlist_video_stats,
    get_video,
    get_video_stats,
    get_videos_published,
    upsert_video,
)

__all__ = [
    "complete_sync_run",
    "create_sync_run",
    "delete_playlist_items",
    "delete_playlists_not_in",
    "delete_videos_not_in",
    "fail_sync_run",
    "get_aggregated_analytics",
    "get_aggregated_traffic_sources",
    "get_all_playlists",
    "get_all_video_ids",
    "get_all_videos",
    "get_connection",
    "get_earliest_published_year",
    "get_fx_rates",
    "get_last_analytics_date",
    "get_last_fx_rate",
    "get_last_successful_run_completed_at",
    "get_last_traffic_source_date",
    "get_playlist",
    "get_playlist_aggregated_analytics",
    "get_playlist_aggregated_traffic_sources",
    "get_playlist_top_videos_by_traffic_source",
    "get_playlist_top_videos_by_views",
    "get_playlist_video_stats",
    "get_playlist_videos",
    "get_sync_runs",
    "get_top_videos_by_traffic_source",
    "get_top_videos_by_views",
    "get_video",
    "get_video_analytics",
    "get_video_stats",
    "get_video_traffic_sources",
    "get_videos_published",
    "init_db",
    "upsert_fx_rate",
    "upsert_playlist",
    "upsert_playlist_item",
    "upsert_video",
    "upsert_video_analytics",
    "upsert_video_traffic_source",
]
